language: node_js
node_js: stable
branches:
  only:
    - master

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build
  - yarn docs:build

after_success:
  - cd ./docs-dist
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add .
  - git commit -m "Build docs $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages
# E: Build LifeCycle
